### ISSUE TITLE
 where is the WebGL2Renderer ?

### ISSUE THREAD

**Issue by psychehao** [spbooks/html5games1#7]
where is the WebGL2Renderer ?

**Comment by simonmackie** [comment]
Paging @mrspeaker

**Comment by mrosshcm** [comment]
@simonmackie: @mrspeaker hasn't contributed to a public repo since Oct. 1, so I would hold my breath for a WebGL renderer.

**Comment by mrspeaker** [comment]
Hey all, sorry for going awol. Life throwing curve balls. The web renderer is over in the [Pop-Game repo](https://github.com/mrspeaker/pop-game). You can choose to use the web renderer in the `Game` constructor. I'll add a link in the code.

It's only the basic version (not handling shader switching) - but it shows how to it works in practice.

**Comment by psychehao** [comment]
@mrlagmer thx,i well take this
